### PR TITLE
Generate .travis.yml via haskell-ci

### PR DESCRIPTION
**Pull request by curiousleo**
Cherry-picked from https://github.com/idontgetoutmuch/random/pull/148.

### CODE REVIEW

**Comment by curiousleo** [comment]
I'm actually not sure how the coveralls integration works - @lehins, do we need to register the `haskell/random` project on coveralls.io or something like that?

**Comment by lehins** [comment]
I am not quite sure, I've never setup coveralls for packages that aren't on my account. I do see `haskell/random` in my coveralls account, but that doesn't mean I have access to control it. 

So maybe @Bodigrim can help us with that, since he's part of haskell org.

What needs to happen is
* coveralls enabled for `haskell/random`
* token from coveralls needs to be added as env var to travis CI
* then `stack-hpc-coveralls` can upload reports.


What I recommend though. Let's merge the current work from #62  into master and then we can fix travis and coveralls, it will be easier to do that on the actual repository rather than from a fork.

**Comment by curiousleo** [comment]
@lehins wrote:

> What needs to happen is
> 
>     * coveralls enabled for `haskell/random`
> 
>     * token from coveralls needs to be added as env var to travis CI
> 
>     * then `stack-hpc-coveralls` can upload reports.

Step 1 looks to be done: https://coveralls.io/github/haskell/random exists - thanks @Bodigrim! Do you have access to Travis for this repo too to add the token as an environment variable?

**Comment by curiousleo** [comment]
Closing in favour of https://github.com/idontgetoutmuch/random/pull/148.

**Pull request closed without merging**
