### PR TITLE
Whitespace cleanup

### PR DESCRIPTION
**Pull request by bgamari**
With GHC now warning for whitespace issues this seems like as good a
time as any.

Given the low patch-volume of this package, I don't believe the monolithic nature of this change should harm anyone.

### CODE REVIEW

**Comment by cartazio** [comment]
@bgamari  travis seems to think your patch is broken :/

**Comment by bgamari** [comment]
@cartazio whoops, didn't push.

**Comment by cartazio** [comment]
@bgamari  is there anything in this  PR that isn't subsumed by pr #22 ?

**Comment by bgamari** [comment]
Nope.

**Pull request closed without merging**
