### PR TITLE
detab

### PR DESCRIPTION
**Pull request by hvr**
since GHC 7.10 has `-fwarn-tabs` on by default

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@ekmett Ping.

**Comment by ekmett** [comment]
I'll merge it as it is an obvious, non-controversial, patch but Dominic Steinitz (@idontgetoutmuch) is the maintainer these days.

**Comment by cartazio** [comment]
Somehow I didn't notice the prs.   My bad

**Comment by 23Skidoo** [comment]
@ekmett Thanks!

**Pull request merged**
