### PR TITLE
Fix broken link to Hellekalek

### PR DESCRIPTION
**Pull request by bgeron**

### CODE REVIEW

**Comment by cartazio** [comment]
hrm... while DOI are useful links, i dont think its acceptable for us to have a URL that lands on a paywall, i'll think of some approach, hrmm

**Comment by bgeron** [comment]
I've added another direct link to a uni-hosted PDF. I think we should keep the DOI because it is a permanent reference and URL links rot heavily, especially on university websites. What do you think?

**Comment by bgeron** [comment]
Bump.

**Comment by lehins** [comment]
We no longer link to this paper. Also the fixed link is now broken too ;) Although pdf is downloadable.

**Pull request closed without merging**
