### PR TITLE
A New Random Proposal

### PR DESCRIPTION
**Pull request by idontgetoutmuch**
A placeholder - sadly no CI seems to have been triggered.

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
### CI
It seems that there are two problems:
1. The link in README.md is not correct, but https://travis-ci.org/github/haskell/random works and even has some builds. 
2. Travis was building the PRs at some point but stopped. I believe that this is due to changes in Travis/Github. To fix it, the owner of this repo or person with the right permissions should restart this feature (turn _Settings|General|Build pushed pull requests_ off and on again). @cartazio are you the one with the power to fix that?

@idontgetoutmuch If you are eager to see the CI build results or want to make sure that it will build on Travis you can enable Travis for your account and turn builds on your fork repo (it is free as it is a public repo). After doing this, you should see the build results here: https://travis-ci.org/github/idontgetoutmuch/random

**Comment by idontgetoutmuch** [comment]
> @idontgetoutmuch If you are eager to see the CI build results or want to make sure that it will build on Travis you can enable Travis for your account and turn builds on your fork repo (it is free as it is a public repo). After doing this, you should see the build results here: https://travis-ci.org/github/idontgetoutmuch/random

@gdziadkiewicz I am indeed eager and thank you very much :)

**Comment by cartazio** [comment]
This is a lovely starting point! I’ll integrate it with the work I have for a new release.  There’s gonna be some differences but there’s certainly some overlap. 

To be clear i can’t and won’t merge this version in.  But I will be able to bring some parts of this pr work into the new release and that’s gonna be great.  

Stay tuned.

**Comment by cartazio** [comment]
(So don’t worry about tweaking the pr :))

**Comment by cartazio** [comment]
Closing for now.  But I’ll refer back to parts of this for the new release. Great work

**Comment by lehins** [comment]
@cartazio I understand that you've been trying to do something with `random` for past few years with nothing to show for. Quite a few people in the community are really not happy with current state of `random` package including myself. That is why some of us gathered together in order to get an improved version out there.

Now let me ask, why do you want to stand in the way. Why are you trying to prevent people in the community to get something the right way instead of waiting for YOUR way?

If you have an upgraded version of `random` then let everyone see it. Let people review it. Let people try it, before you decide what's best for everyone else. We are here to provide constructive feedback, because we all trying to achieve the common goal of better `random` library for everyone to use.

If you'd rather do it all by yourself, but your new version is not ready yet, then give us a deadline when will you have it ready. Cause not only we are tired of waiting, but we are also converging onto something that is 100% better than the current version on Hackage that is almost 6 years old.

**Comment by cartazio** [comment]
It’s not a clean merge.  I literally have to do surgery to combine them.
Nothing deeper than that.

**Comment by lehins** [comment]
@cartazio picking and choosing bits and pieces that YOU want out of a bigger initiative is not proper collaboration and not the right way to do software development. We've repeatedly invited you to work together, so we can discuss each individual feature and go through peer review for each of them, together! Instead of doing "surgery" it would be better to submit a PR to the work that we done so far, so we can _together_, bring this project to success.

You are trying to do everything yourself that is why this project has been stuck for all these years.

**Comment by cartazio** [comment]
well, its alraedy in merge conflict on master which has some parts of the change, just not the new type class, that still needs some workshopping 

stuff already in master (that )
1) in tree inclusion of pcg32 (64bit state) and splitmix  -- having a few really good quality ones in tree so that theres no dependency inversion going on 
2) a whole mess of nice sampler combinators with a generic monadic interface for bounded range intervals and some continuous distributions, with a few other wips threrein.

this whole NYC  (and the world) being a FEMA zone has me a tad spread thin and stressed, but expositing the rest is on my list of things to do. (just need to manage stress)

**Comment by cartazio** [comment]
a number of monadic combinators are in https://github.com/haskell/random/tree/master/src/Data/Distribution  this directory

the good statsitical PRNGs are already in tree
https://github.com/haskell/random/tree/master/src/System/Random/PCG32 
https://github.com/haskell/random/blob/master/src/System/Random/SplitMix/Internal.hs

**Pull request closed without merging**
