### PR TITLE
initialise github ci

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by Bodigrim** [comment]
@lehins @Shimuuar Anyone recalls what incantation is missing for doctests? Same with https://github.com/haskell/vector/pull/340
We also need to figure out how to run coverage report.

**Comment by lehins** [comment]
@Bodigrim Hold off on this PR. I have a better solution coming up

**Comment by lehins** [comment]
@chessai and @Bodigrim please see a working solution using `stack` in #86

**Comment by lehins** [comment]
Closing in  favor of #86

**Pull request closed without merging**
