### PR TITLE
Getting rid of TAB characters

### PR DESCRIPTION
**Pull request by trskop**
This causes a lot of warnings while compiling, since -fwarn-tabs is
enabled by default.

### CODE REVIEW

**Comment by cartazio** [comment]
There's already a pr for this.  But also the next release of random is
going to be a total rewrite so it won't have the issue :)

**Comment by cartazio** [comment]
this work will be subsumed by #31

**Comment by xkollar** [comment]
Well... but till then... would you consider at least releasing minor release? This patch looks good and it would remove quite some warnings people encounter on daily basis (which make it harder to notice significant warnings)... And from bootstraping cabal...

Please consider accepting this patch (at least for some branch for minor release...).

**Comment by cartazio** [comment]
Okkkay.  I'll dig into that later today.

**Comment by trskop** [comment]
There is also another possibility. Tell GHC to ignore that warning by passing `-fno-warn-tabs` option by using either `ghc-options` field in package Cabal file, or `OPTIONS_GHC` pragma.

**Comment by cartazio** [comment]
I'll be getting back on the horse this wekeend.

Also in what context are these warnings creating real problems ?

**Comment by Siprj** [comment]
I think that warnings really are big issue... I have to believe my build script to correctly skip warnings from "random" library and if something happens in build process I have to go through all these warnings manually.

I agree with @xkollar, this PR looks good. I don't see any problem that may come up with releasing minor version.

**Comment by cartazio** [comment]
what build script is doing -WERROR  on dependencies warnings? thats a bug
in your build script / ci process

but yes, i'll get to this soon, have some other release engineering
underway this week

**Pull request closed without merging**
